### ISSUE TITLE
Function ellipse not found while building vignettes

### ISSUE THREAD

**Issue by gaballench** [JClavel/mvMORPH#10]
Dear Dr. Clavel,

I tried to install mvMORPH using `install_github` but there is an error when compiling the rmd suggesting the function `ellipse` (used in this line https://github.com/JClavel/mvMORPH/blob/ca044d7cbb9314de04bf2f693d5567b409b529b1/vignettes/tutorial_mvMORPH.Rmd#L330) is not found. Which package does provide this function?

Thanks in advance,

Gustavo

**Comment by JClavel** [comment]
Dear Gustavo,

To build a vignette you need packages that are usually in the "Suggests" section of the NAMESPACE.
Here, you'll need both "knitr" and "car"

Regards,

Julien
