### ISSUE TITLE
mvgls constant crash

### ISSUE THREAD

**Issue by Wxdeyyy** [JClavel/mvMORPH#12]
I have been unable to successfully run the mvgls function, however there aren't any error messages- the R session (in both Rstudio and the base R terminal) terminates  with no pointers/indication about how to fix it. 

Please advise, happy to share the metadata and code that triggers this

**Comment by JClavel** [comment]
Hi,
Try to run first the examples on the help page of “mvgls”. If they work, then it’s probably an issue with the formatting of your data, if not it might be an issue with missing dependencies.
I can’t advise more without a reproducible example.
Regards,
Julien
