### ISSUE TITLE
Error in mvOU

### ISSUE THREAD

**Issue by rafmarcondes** [JClavel/mvMORPH#2]
I'm getting the following error when I try running mvOU:

> mvOUM_f=mvOU(tree=map_tr, data=mvmorph_input, model='OUM', echo=F)
Error in optim(par = c(alpha, sigma), fn = function(par) { : 
  L-BFGS-B needs finite values of 'fn'

mvBM seems to run normally.

mvMORPH 1.0.9
R 3.3.3
Mac OS 10.12.5

[map_tr.R.zip](https://github.com/JClavel/mvMORPH/files/1208737/map_tr.R.zip)
[mvmorph_input.R.zip](https://github.com/JClavel/mvMORPH/files/1208736/mvmorph_input.R.zip)

**Comment by rafmarcondes** [comment]
Please suggest a workaround, if there is any.

**Comment by JClavel** [comment]
Dear Rafael,


I'm sorry I can't open the files you embodied in the gitHub issue page. So I can't reproduce your error.

This kind of message probably mean that there were a problem when computing the log-likelihood. It's possibly a singularity issue. Try using safer algorithms such as method="inverse", or method="pseudoinverse" (although slower...). There are some more informations about the various algorithms on the package vignette.


Please send codes and related dataset by mail, it will be easier to track.


All the best,


Julien


________________________________
De : Rafael Marcondes <notifications@github.com>
Envoyé : mardi 8 août 2017 17:51
À : JClavel/mvMORPH
Cc : Subscribed
Objet : [JClavel/mvMORPH] Error in mvOU (#2)


I'm getting the following error when I try running mvOU:

mvOUM_f=mvOU(tree=map_tr, data=mvmorph_input, model='OUM', echo=F)
Error in optim(par = c(alpha, sigma), fn = function(par) { :
L-BFGS-B needs finite values of 'fn'

mvBM seems to run normally.

mvMORPH 1.0.9
R 3.3.3
Mac OS 10.12.5

map_tr.R.zip<https://github.com/JClavel/mvMORPH/files/1208737/map_tr.R.zip>
mvmorph_input.R.zip<https://github.com/JClavel/mvMORPH/files/1208736/mvmorph_input.R.zip>
