### ISSUE TITLE
Upper and lower arguments in mvgls()

### ISSUE THREAD

**Issue by cdmuir** [JClavel/mvMORPH#4]
The documentation file for the `mvgls()` function indicates that lower/upper bounds on the parameter search should be provided with the `lower = ` and `upper = ` arguments, as in `optim()`. e.g.

`mvgls(trait ~ x, data, tree, "OU", lower = 0, upper = 1)`

This doesn't work. The argument names should be `low = ` and `up = `. e.g.

`mvgls(trait ~ x, data, tree, "OU", low = 0, up = 1)`

Change documentation or change code from:

```
    if (is.null(args[["up"]])) 
        up <- NULL
    else up <- args$up
    if (is.null(args[["low"]])) 
        low <- NULL
    else low <- args$low
```

to 

```
    if (is.null(args[["upper"]])) 
        up <- NULL
    else up <- args$upper
    if (is.null(args[["lower"]])) 
        low <- NULL
    else low <- args$lower
```

**Comment by JClavel** [comment]
Hello,

Thank you for reporting the issue. I changed the code in mvgls to accept the "upper" and "lower" arguments as suggested.

Thanks again,

Julien
