### ISSUE TITLE
Could not find function "EIC" or "manova.gls"

### ISSUE THREAD

**Issue by corinthiablack** [JClavel/mvMORPH#6]
I tried some example data to learn the package, but I ran into an issue with functions 'EIC' and 'manova.gls'. The errors say the functions are not found in the package. The package version is 1.1.0, which was loaded from CRAN.

**Comment by JClavel** [comment]
Hi Corinthia,

Indeed, the 1.1.0 version is more than 2 years old now. Try instead to install the last version on CRAN (1.1.3) or better (i.e., with up to date fixes), the devel one (1.1.4) from gitHub :

`
library(devtools)

install_github("JClavel/mvMORPH", ref="devel_1.0.4")
`

(Note that you may also need to install Rtools or some compilers to compile the C codes included in the package if you're installing from gitHub with devtools. For [Windows] (https://cran.r-project.org/bin/windows/Rtools/) and for [Mac] (http://r.research.att.com) (and [Tools] (https://r.research.att.com/tools/) )

HTH,

Julien
